server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ezgear-backend

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: 123456
#    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # dev th� ?? update, prod th� n�n ??i th�nh none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 3s
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      enabled: false

    mongodb:
      uri: ${MONGO_URI}

    elasticsearch:
      repositories:
        enabled: true

  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: ${SENDGRID_FROM_EMAIL}
    templateOrderSuccessfulId: ${SENDGRID_TEMPLATE_ORDER_ID}
    templateOrderShippingId: ${SENDGRID_TEMPLATE_SHIPPING_ID}
    verificationLink: ${SENDGRID_VERIFICATION_LINK}

jwt:
  expiryMinutes: ${JWT_EXPIRY_MINUTES}
  expiryDay: ${JWT_EXPIRY_DAY}
  accessKey: ${JWT_ACCESS_KEY}
  refreshKey: ${JWT_REFRESH_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs       # custom path cho OpenAPI JSON

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
google:
  client-id: ${GOOGLE_CLIENT_ID}
  secret: ${GOOGLE_CLIENT_SECRET}
ghn:
  env: staging
  base-url:
    staging: https://dev-online-gateway.ghn.vn/shiip/public-api
    production: https://online-gateway.ghn.vn/shiip/public-api
  token:
    staging: ${GHN_STAGING_TOKEN}
    production: ${GHN_PRODUCTION_TOKEN}
  shop-id:
    staging: ${GHN_STAGING_SHOP_ID}
    production: ${GHN_PRODUCTION_SHOP_ID}
vnpay:
  tmnCode: 2NXP4AJZ           # mã merchant VNPay cấp
  hashSecret: 98TOBQT0FCTVIBL19AU4ANDOWOYL1FUO     # chuỗi bí mật dùng để ký
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/api/payment/vnpay/return
  callbackUrl: http://localhost:8080/api/payment/vnpay/callback


#  Ngân hàng	NCB
#  Số thẻ	9704198526191432198
#  Tên chủ thẻ	NGUYEN VAN A
#  Ngày phát hành	07/15
#  Mật khẩu OTP	123456